### ISSUE TITLE
Set license for config

### ISSUE THREAD

**Issue by ghost** [s0me1newithhand7s/myNixConf#11]
if you do not specify a license, your project is considered proprietary by default.

I suggest setting up some kind of permissive license, for example Unlicense or WTFPL, so that people can open merge requests, fork the config and customize it for themselves.

Not GPLv3, since no one will fork your config and sell it for money, since they simply won’t buy it. And if you install the GPLv3 license, you will not be able to change the license in the future. Just don’t use the Unlicense or WTFPL license for programs, as they can be sold. GPLv3 is better for programs.

How to apply the WTFPL license: http://www.wtfpl.net/faq/
How to apply the Unlicense license: https://unlicense.org/

**Comment by s0me1newithhand7s** [comment]
i'll set MIT. xD

**Comment by Aserogl31** [comment]
@s0me1newithhand7s you did not set MIT, there is no COPYING or LICENSE file in the project

**Comment by ghost** [comment]
@s0me1newithhand7s, can you set a license for other projects?

**Comment by s0me1newithhand7s** [comment]
> @s0me1newithhand7s, can you set a license for other projects?

i don't feel like dots needed to be licensed, so

**Comment by ghost** [comment]
@s0me1newithhand7s, then no one will be able to send u pullrequests
